DATA SEGMENT
    ARR DW 1111,2222,3333,4444,5555
    LARGE DW ?
    COUNT DB 5
DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE DS:DATA
    START:
    MOV AX,DATA
    MOV DS,AX
    MOV CL,COUNT
    LEA SI,ARR
    MOV BX,[SI]
    INC SI
    INC SI
    AGAIN:
    CMP [SI],BX
    JL NOCHANGE
    MOV BX,[SI]
    NOCHANGE:
        INC SI
        INC SI
        DEC CL
        JNZ AGAIN
    MOV LARGE,BX
    MOV AH,4CH
    INT 21H
CODE ENDS
END START
